### PR TITLE
add notificationSecret

### PR DESCRIPTION
**Pull request by usamaahmadkhan**

### CODE REVIEW

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-e2e-tests/job/PR-2/1/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-e2e-tests/job/PR-2/4/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-e2e-tests/job/PR-2/5/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-e2e-tests/job/PR-2/6/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-e2e-tests/job/PR-2/7/) has Failed!

**Review by aliartiza75 — APPROVED** [review]

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 9](https://jenkins-delivery.workshop.stakater.com/job/NordMart%20Application/job/stakater-nordmart-e2e-tests/job/PR-2/9/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Tests have been passed!

**Pull request merged**
